name: Deploy-Android-TEST

on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+([0-9]+)'

env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_APPIUMDEMO_ANDROID_TEST  }}
  APP_NAME: ${{ 'TestRadix/ENV_TEST'  }}
  TESTING_GROUP: ${{  'ENV_TEST'  }}
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/app-release.apk'  }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: set up JDK 18.0.1.1
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: 18.0.1.1

      - name: Install dependencies
        run: npm install

      - name: Build android
        run: cd android && ./gradlew assembleRelease

      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: ${{ env.TESTING_GROUP }}
          file: ${{ env.UPLOAD_FILE }}
          notifyTesters: true
          debug: false
